### ISSUE TITLE
Grouper puis pivoter un ecolonne

### ISSUE THREAD

**Issue by mmaurais** [MicrosoftDocs/powerbi-docs.fr-fr#10]
Bonjour,
J'ai 4 lignes avec des info identique mais les lignes ont des temps différents dans 1 des colonnes
Je voudrais regrouper ces 4 lignes, et que les temps apparaissent dans 4 nouvelles colonnes
Je peux grouper et pivoter la colonne du temps, mais ça va me donner 600 colonnes pour chaque ligne et seulement 4 des 600 seront utilisées à chaque ligne
Avez-vous une piste de solution ?

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 90ca589e-10e9-3924-a3ac-c774368cdec6
* Version Independent ID: 2c7f64d7-8306-1622-6ca3-912b805acf0c
* Content: [Tâches courantes relatives aux requêtes dans Power BI Desktop - Power BI](https://docs.microsoft.com/fr-fr/power-bi/desktop-common-query-tasks#feedback)
* Content Source: [powerbi-docs/desktop-common-query-tasks.md](https://github.com/MicrosoftDocs/powerbi-docs.fr-fr/blob/live/powerbi-docs/desktop-common-query-tasks.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**
<img width="603" alt="2019-06-03 11_08_46-Ber_gestion des produit - Éditeur Power Query" src="https://user-images.githubusercontent.com/51330690/58812527-10157e00-85f0-11e9-813a-31db08649747.png">

**Comment by CeciAc** [comment]
Bonjour @mmaurais

Merci pour votre contribution. Notre équipe peut uniquement répondre au feedback qui porte sur la documentation. 

Pour envoyer vos commentaires produit, nous vous invitons à cliquer sur le bouton « Envoyer des commentaires sur le produit » situé au bas de la page Docs. 

Si vous avez des commentaires sur la documentation, n’hésitez pas à nous les envoyer via ce canal. 

Votre contribution à nos articles est grandement appréciée.  

Cordialement, 
L’équipe Microsoft DOCS International
