### ISSUE TITLE
ArcGIS Maps to PDF

### ISSUE THREAD

**Issue by Bulbute** [MicrosoftDocs/powerbi-docs.fr-fr#11]
Bonjour, J'ai un problème lorsque j'exporte en pdf un rapport avec des cartographie ArcGIS maps. Elles n'ont pas le temps de charger et je sors un PDF avec une image de carte "en charge" avec les points de suspensions. Je veux garder les cartes dynamiques lorsque je les envoie en format numérique mais j'aimerais avoir un aperçu de la carte par défaut sur les fichiers PDF.
Merci

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: e7dd54f0-efd3-c6df-7129-e2affa3ae942
* Version Independent ID: cc7bd663-267f-21d5-547b-b3d8614005fd
* Content: [Exporter vos rapports au format PDF à partir de Power BI Desktop - Power BI](https://docs.microsoft.com/fr-fr/power-bi/desktop-export-to-pdf#feedback)
* Content Source: [powerbi-docs/desktop-export-to-pdf.md](https://github.com/MicrosoftDocs/powerbi-docs.fr-fr/blob/live/powerbi-docs/desktop-export-to-pdf.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by CeciAc** [comment]
Bonjour @Bulbute

Merci pour votre contribution. Notre équipe peut uniquement répondre au feedback qui porte sur la documentation. 

Pour envoyer vos commentaires produit, nous vous invitons à cliquer sur le bouton « Envoyer des commentaires sur le produit » situé au bas de la page Docs. 

Si vous avez des commentaires sur la documentation, n’hésitez pas à nous les envoyer via ce canal. 

Votre contribution à nos articles est grandement appréciée.  

Cordialement, 
L’équipe Microsoft DOCS International
