### ISSUE TITLE
Mauvais lien ou fonctionnalité supprimée

### ISSUE THREAD

**Issue by ldeoux** [MicrosoftDocs/powerbi-docs.fr-fr#12]
Bonjour
Le liens vers le téléchargement du module Power BI Publisher pour Excel renvoi sur la page de Excel Analyser…
Excel Analyser permet d'analyser des donner PowerBI dans Excel… ce n'est pas ce que je veux… Je veux afficher un Tableau de bord Excel dans PowerBI…
Cette fonction n'est plus valide ou est ce le lien qui est tout simplement invalide ?
Merci de votre retour
Cordialement

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 458afd24-a62a-7944-5cd4-de9a9290c308
* Version Independent ID: ed6a56f0-e067-9f92-5d54-6755b49f3bc0
* Content: [Utiliser Power BI Publisher pour Excel - Power BI](https://docs.microsoft.com/fr-fr/power-bi/publisher-for-excel#feedback)
* Content Source: [powerbi-docs/publisher-for-excel.md](https://github.com/MicrosoftDocs/powerbi-docs.fr-fr/blob/live/powerbi-docs/publisher-for-excel.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/powerbi-docs #1160](https://github.com/MicrosoftDocs/powerbi-docs/issues/1160) via [**ZenHub**](https://www.zenhub.com/)
