### ISSUE TITLE
For Local Datasources Power BI Dataflow creation is rectricted to Enterprise Gateway Admins only...

### ISSUE THREAD

**Issue by lyesd** [MicrosoftDocs/powerbi-docs.fr-fr#13]
Hi,
Power Bi Dataflow is an excellent way to industrialize and centralize duplicated PowerQuery flows through an organization.

According to this page, in order to create a PBI dataflow the user has to be an Enterprise Gateway Admin.
I hope that this restriction will be retrieved for the GA release...
In many businesses BI Analysts are not necessarily Enterprise Gateway Administrators.
This role is limited to very few organization members.
Therefore PBI Dataflow creation is restricted and can't be used efficiently in an organization...

Would you guys consider applying the same process than the one for report publishing (using local data sources)?

Lyes

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 305e8837-917d-43d4-4d09-a180082f3ab8
* Version Independent ID: b43bfaf7-d7e1-a715-1ffa-e1f9e78371e8
* Content: [Utilisation de flux de données avec des sources de données locales - Power BI](https://docs.microsoft.com/fr-fr/power-bi/service-dataflows-on-premises-gateways#feedback)
* Content Source: [powerbi-docs/service-dataflows-on-premises-gateways.md](https://github.com/MicrosoftDocs/powerbi-docs.fr-fr/blob/live/powerbi-docs/service-dataflows-on-premises-gateways.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by lichasu** [comment]
Hello, @lyesd 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
