### ISSUE TITLE
La base de données de correspond pas aux explications

### ISSUE THREAD

**Issue by ChristopheRpp** [MicrosoftDocs/powerbi-docs.fr-fr#15]
Bonjour,
La base de données qu'on trouve sur :
https://www.bankrate.com/finance/retirement/best-places-retire-how-state-ranks.aspx
n'est plus celle qui est utilisé dans le tuto.
Idem pour celle de la fusion de base de donnée.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 7bf2015c-41fe-8234-dd4d-698e589b6fc7
* Version Independent ID: bc0deeb1-04c7-abc3-b26c-10ea6d75c57f
* Content: [Prise en main de Power BI Desktop - Power BI](https://docs.microsoft.com/fr-fr/power-bi/desktop-getting-started#feedback)
* Content Source: [powerbi-docs/desktop-getting-started.md](https://github.com/MicrosoftDocs/powerbi-docs.fr-fr/blob/live/powerbi-docs/desktop-getting-started.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by srvbpigh** [comment]
Hello, @ChristopheRpp
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/powerbi-docs #1624](https://github.com/MicrosoftDocs/powerbi-docs/issues/1624) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Bonjour @ChristopheRpp

Merci pour votre contribution. Votre feedback porte sur la documentation en langue anglaise. 

Nous l’avons donc transféré au dépôt Anglais. Vous pouvez consulter le statut de votre demande ici : https://github.com/MicrosoftDocs/powerbi-docs/issues/1624

Votre contribution à nos articles est grandement appréciée.  

Cordialement, 
L’équipe Microsoft DOCS International

**Comment by ChristopheRpp** [comment]
Bonjour Ceci,
Y a-t-il quelque part un tuto en Français ? S'il existe, je préfèrerais...
Christophe
