### ISSUE TITLE
Tri : Choix dans une colonne

### ISSUE THREAD

**Issue by DEBOV** [MicrosoftDocs/powerbi-docs.fr-fr#16]
Bonjour, 

Existe t il un moyen de trier un champ Texte autrement que par ordre alphabétique ? 
Exemple: Champ X mis en colonne dans un tableau dynamique avec les données suivantes :
- Interco
- Invoice
- Outstanding
- Pick Pack
- Reserved

Comment faire pour trier de les colonnes comme: 
1 Outstanding
2 Reserved
3 Pick Pack
4 Interco
5 Invoice 

Merci à vous, 
V.
---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: bc6eda16-f142-5163-b0af-38fa634d7e42
* Version Independent ID: 58599a34-91ac-4947-c2e5-a0508a554080
* Content: [Trier par colonne dans Power BI Desktop - Power BI](https://docs.microsoft.com/fr-fr/power-bi/desktop-sort-by-column#feedback)
* Content Source: [powerbi-docs/desktop-sort-by-column.md](https://github.com/MicrosoftDocs/powerbi-docs.fr-fr/blob/live/powerbi-docs/desktop-sort-by-column.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by srvbpigh** [comment]
Hello, @DEBOV
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Bonjour @DEBOV,

Merci pour votre contribution. Notre équipe peut uniquement répondre au feedback qui porte sur la documentation. 

Pour envoyer vos commentaires produit, nous vous invitons à cliquer sur le bouton « Envoyer des commentaires sur le produit » situé au bas de la page Docs. 

Si vous avez des commentaires sur la documentation, n’hésitez pas à nous les envoyer via ce canal. 

Votre contribution à nos articles est grandement appréciée.  

Cordialement, 
L’équipe Microsoft DOCS International
