### ISSUE TITLE
Un autre tutoriel

### ISSUE THREAD

**Issue by ChristopheRpp** [MicrosoftDocs/powerbi-docs.fr-fr#17]
Bonjour
Ce tutoriel n'est plus utilisable parce que les données qu'ils utilisent ne sont plus disponibles (et donc on ne peut pas le suivre). Auriez-vous un autre tutoriel (en Français si possible) a nous conseiller ?
Cordialement
Christophe

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 7bf2015c-41fe-8234-dd4d-698e589b6fc7
* Version Independent ID: bc0deeb1-04c7-abc3-b26c-10ea6d75c57f
* Content: [Prise en main de Power BI Desktop - Power BI](https://docs.microsoft.com/fr-fr/power-bi/desktop-getting-started)
* Content Source: [powerbi-docs/desktop-getting-started.md](https://github.com/MicrosoftDocs/powerbi-docs.fr-fr/blob/live/powerbi-docs/desktop-getting-started.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by srvbpigh** [comment]
Hello, @ChristopheRpp
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Bonjour @ChristopheRpp

Merci pour votre contribution. Notre équipe a examiné vos commentaires et il semble que ce problème ait déjà été signalé. 

Je vous invite à consulter le problème n° https://github.com/MicrosoftDocs/powerbi-docs/issues/1627
Pour éviter un doublon, nous avons clos le problème que vous nous avez signalé. 

Cordialement, 
L’équipe Microsoft DOCS International
