### ISSUE TITLE
Getting the May report .pbix

### ISSUE THREAD

**Issue by Didierma92** [MicrosoftDocs/powerbi-docs.fr-fr#18]
Hi, I need to do a demo for sales report. I would like to get the may report file, and show the May report which is visible in this documentation. How could I download this report ?

**Comment by srvbpigh** [comment]
Hello, @Didierma92
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @Didierma92 

Your contribution is much appreciated. Yet, this feedback is related with the product, please kindly log by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles.
	
Kind regards,
Microsoft DOCS International Team
