### ISSUE TITLE
"L'accès à la ressource est interdit"

### ISSUE THREAD

**Issue by Bulbute** [MicrosoftDocs/powerbi-docs.fr-fr#19]
Bonjour, 
Lorsque je colle mon lien sharepoint en supprimant le "?" et ce qui suit. Power BI ne m'ouvre pas la fenêtre d'identification mais me renvoie une fenêtre : "Connexion impossible, Nous avons rencontré une erreur lors de la tentative de connexion. Détails : "L'accès à la ressource est interdit.". Je ne sais pas comment faire, avez-vous une idée ?
D'avance merci,
Bien cordialement,

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 92a1e2f2-6f7a-06ab-77a5-efff8aedabe3
* Version Independent ID: 67d3cd28-51ec-07d9-ed36-840097415f56
* Content: [Utilisation des liens OneDrive Entreprise dans Power BI Desktop - Power BI](https://docs.microsoft.com/fr-fr/power-bi/desktop-use-onedrive-business-links)
* Content Source: [powerbi-docs/desktop-use-onedrive-business-links.md](https://github.com/MicrosoftDocs/powerbi-docs.fr-fr/blob/live/powerbi-docs/desktop-use-onedrive-business-links.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by srvbpigh** [comment]
Hello, @Bulbute
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Bonjour @Bulbute 

Votre contribution est très appréciée. Ces commentaires concernant un produit, nous vous invitons à enregistrer votre suggestion en utilisant le bouton « Envoyer des commentaires sur le produit » qui se trouve au bas de la page DOCS.

Si vous avez des commentaires relatifs à la documentation, n'hésitez pas à les communiquer par ce canal.

Nous apprécions réellement votre contribution à nos articles.

L’équipe internationale de Microsoft DOCS

**Comment by Nibz-lab** [comment]
Bonjour, J'ai exactement le même pb « L'accès à la ressource est interdit. »
Avez-vous trouvé une solution ? Merci
