### ISSUE TITLE
Power BI online/ desktop

### ISSUE THREAD

**Issue by cherif22** [MicrosoftDocs/powerbi-docs.fr-fr#2]
what is difference between power Bi desktop and power Bi online and when  i used ?

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: d877b0ce-2e0b-dca4-709d-24b4e5a374b4
* Version Independent ID: 8d727d5a-7e46-62a7-8530-882ee9653640
* Content: [Questions fréquentes dans Power BI - Power BI](https://docs.microsoft.com/fr-fr/power-bi/service-frequently-asked-questions#feedback)
* Content Source: [powerbi-docs/service-frequently-asked-questions.md](https://github.com/MicrosoftDocs/powerbi-docs.fr-fr/blob/live/powerbi-docs/service-frequently-asked-questions.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by LisandroSu** [comment]
Hello, @cherif22 , 
 
Your contribution is much appreciated. Our team can only answer feedback related to the documentation. 
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page. 
 
If you have any feedback related to the documentation, please feel free to log it through this channel. 
We truly appreciate your contribution to our articles.  
 
Kind regards, 
Microsoft DOCS International Team
