### ISSUE TITLE
Afficher graphique issu table sur point carte géo localisé précisément (long-lat 191015FG.pbix) ?

### ISSUE THREAD

**Issue by MANTE49** [MicrosoftDocs/powerbi-docs.fr-fr#23]
Bonjour, POWER BI DESKSTOP je ne réussis pas à mettre un ou plusieurs graphiques simples issus de ma table sur chaque chef-lieu de région d'un pays, pourtant localisés sans problème (longitude/latitude). Pourtant dans un tuto même de PBI (visuel/Disposition et mise en forme), une visualisation illustre que c'est possible (carte USA) mais ne dit pas comment faire. 
Quelqu'un peut-il me dire comment afficher un ou plusieurs graphiques issus de ma table sur un point géolocalisé précisément (long/lat) ? (voir 191015FG.pbix page 1 publié si besoin°

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 735d805a-0981-4f84-12e7-b5560ea9c3bb
* Version Independent ID: d5dce962-ecf1-014e-65d9-00121fdd6d3c
* Content: [Conseils et astuces pour les cartes (y compris l’intégration Bing Maps) - Power BI](https://docs.microsoft.com/fr-fr/power-bi/visuals/power-bi-map-tips-and-tricks#feedback)
* Content Source: [powerbi-docs/visuals/power-bi-map-tips-and-tricks.md](https://github.com/MicrosoftDocs/powerbi-docs.fr-fr/blob/live/powerbi-docs/visuals/power-bi-map-tips-and-tricks.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by srvbpigh** [comment]
Hello, @MANTE49
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/powerbi-docs #2065](https://github.com/MicrosoftDocs/powerbi-docs/issues/2065) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @MANTE49, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/powerbi-docs/issues/2065. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
