### ISSUE TITLE
afficher graphique sur point géolocalisé ?

### ISSUE THREAD

**Issue by MANTE49** [MicrosoftDocs/powerbi-docs.fr-fr#24]
Comment faites vous pour afficher un graphique sur un point géolocalisé (longitude/latitude) précisément d'une carte. Les données du graphiques sont dasn la table. Faut-il créér un champ graphique ? Si oui comment ?

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: ad604499-b845-44de-acc9-1bd9a7a97488
* Version Independent ID: f16079ec-98ee-e35d-f928-c5d493365051
* Content: [Personnaliser les propriétés des axes X et Y - Power BI](https://docs.microsoft.com/fr-fr/power-bi/visuals/power-bi-visualization-customize-x-axis-and-y-axis#feedback)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-customize-x-axis-and-y-axis.md](https://github.com/MicrosoftDocs/powerbi-docs.fr-fr/blob/live/powerbi-docs/visuals/power-bi-visualization-customize-x-axis-and-y-axis.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by srvbpigh** [comment]
Hello, @MANTE49
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Bonjour @MANTE49 
Merci pour votre contribution. Notre équipe a examiné vos commentaires et il semble que ce problème ait déjà été signalé.  
Je vous invite à consulter le problème n° https://github.com/MicrosoftDocs/powerbi-docs.fr-fr/issues/25
Pour éviter un doublon, nous avons clos le problème que vous nous avez signalé.  

Cordialement,  

L’équipe Microsoft DOCS International
