### ISSUE TITLE
AFFICHER GRAPHIQUE SUR POINT GeOLOCALISE d'une carte ?

### ISSUE THREAD

**Issue by MANTE49** [MicrosoftDocs/powerbi-docs.fr-fr#25]
Comment faites vous pour afficher un graphique sur un point géolocalisé (longitude/latitude) précisément d'une carte. Les données du graphiques sont dasn la table. Faut-il créér un champ graphique ? Si oui comment ?

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 6d720907-1bee-2523-b53b-a1f2ffad1bfc
* Version Independent ID: b5a1765e-8008-af99-e82f-4e694fb0c75b
* Content: [Changer le mode tri d’un graphique dans un rapport - Power BI](https://docs.microsoft.com/fr-fr/power-bi/consumer/end-user-change-sort)
* Content Source: [powerbi-docs/consumer/end-user-change-sort.md](https://github.com/MicrosoftDocs/powerbi-docs.fr-fr/blob/live/powerbi-docs/consumer/end-user-change-sort.md)
* Service: **powerbi**
* Sub-service: **powerbi-consumer**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by srvbpigh** [comment]
Hello, @MANTE49
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/powerbi-docs #2072](https://github.com/MicrosoftDocs/powerbi-docs/issues/2072) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Bonjour @MANTE49,  

Merci pour votre contribution. Votre feedback porte sur la documentation en langue anglaise.  

Nous l’avons donc transféré au dépôt Anglais. Vous pouvez consulter le statut de votre demande ici : https://github.com/MicrosoftDocs/powerbi-docs/issues/2072.  

Votre contribution à nos articles est grandement appréciée.   

Cordialement,  
L’équipe Microsoft DOCS International
