### ISSUE TITLE
Missing "reader" role

### ISSUE THREAD

**Issue by ThomasKwakman** [MicrosoftDocs/powerbi-docs.fr-fr#26]
Hi,

For the following sentence, the reader role is missing, isn't it?

"Add security groups, distribution lists, Office 365 groups, or individuals to these workspaces as members, contributors, or admins. See Roles in the new workspaces for an explanation of the different roles."

Have a nice day
Best regards
Thomas Kwakman

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 11357d2a-97f6-c5d6-2a62-0d5cae1a1c3d
* Version Independent ID: 51900b79-f5ed-25b8-ee89-9078129bdb15
* Content: [Créer les nouveaux espaces de travail - Power BI - Power BI](https://docs.microsoft.com/fr-fr/power-bi/service-create-the-new-workspaces)
* Content Source: [powerbi-docs/service-create-the-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs.fr-fr/blob/live/powerbi-docs/service-create-the-new-workspaces.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by srvbpigh** [comment]
Hello, @ThomasKwakman
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/powerbi-docs #2082](https://github.com/MicrosoftDocs/powerbi-docs/issues/2082) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @ThomasKwakman, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/powerbi-docs/issues/2082. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
