### ISSUE TITLE
Bravo

### ISSUE THREAD

**Issue by RymMichaut** [MicrosoftDocs/powerbi-docs.fr-fr#3]
MerciMicrosoft pour cette superbe documentation. 
En moins de 8h, j'ai réussi à prendre en main Power BI qui est un outil ultra ergonomique et qui tient sa promesse.
Merci!

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: cbffbf18-2789-7aaa-6f21-08a2a8dd018f
* Version Independent ID: 759b3f52-ab4a-176e-5be3-6e9dc062ca82
* Content: [Publication et partage - Power BI](https://docs.microsoft.com/fr-fr/power-bi/guided-learning/publishingandsharing?tutorial-step=13)
* Content Source: [powerbi-docs/guided-learning/publishingandsharing.yml](https://github.com/MicrosoftDocs/powerbi-docs-pr.fr-FR/blob/live-sxs/powerbi-docs/guided-learning/publishingandsharing.yml)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by LisandroSu** [comment]
Bonjour @RymMichaut 

Merci pour votre feedback. Nous sommes heureux d’apprendre que notre documentation répond à vos attentes. 
Dans une optique d’amélioration constante, nous vous encourageons à envoyer vos commentaires à Microsoft. 

Cordialement, 
L’équipe Microsoft DOCS International
