### ISSUE TITLE
Calcul de la moyenne d'une colonne par modalités d'une autre colonne

### ISSUE THREAD

**Issue by RymMichaut** [MicrosoftDocs/powerbi-docs.fr-fr#6]
Bonjour,
Sur un projet en cours, je n'arrive pas à créer une mesure calculant la moyenne de données dans une colonne B sur chaque modalité d'une colonne A. 

Exemple:
A  B
1  B1
1  B2
1  B3
2  B4
2  B5
3  B6

je veux calculer la moyenne de B1, B2, B3 pour la modalité 1 de la colonne A et la moyenne de B4, B5 pour la modalité 2 de la colonne A... etc.

Je sais qu'on peut le faire à travers les agrégations dans la section "Champs" mais j'ai besoin de cette mesure pour la réutiliser dans le calcul d'une autre mesure.

Quelqu'un pourrait m'expliquer s'il vous plait comment faire?

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: f0509d4c-73e0-1ffe-6e71-965f76ec4e12
* Version Independent ID: d6ea7fca-f40e-5ac3-0d6a-11d072f64fe4
* Content: [Agrégations (somme, moyenne, maximum, etc.) dans les visualisations - Power BI](https://docs.microsoft.com/fr-fr/power-bi/service-aggregates)
* Content Source: [powerbi-docs/service-aggregates.md](https://github.com/MicrosoftDocs/powerbi-docs.fr-fr/blob/live/powerbi-docs/service-aggregates.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by CeciAc** [comment]
Bonjour @RymMichaut, 

Merci pour votre contribution. Notre équipe peut uniquement répondre au feedback qui porte sur la documentation. 

Pour envoyer vos commentaires produit, nous vous invitons à cliquer sur le bouton « Envoyer des commentaires sur le produit » situé au bas de la page Docs. 

Si vous avez des commentaires sur la documentation, n’hésitez pas à nous les envoyer via ce canal. 

Votre contribution à nos articles est grandement appréciée.  

Cordialement, 
L’équipe Microsoft DOCS International
