### ISSUE TITLE
Does Adobe Analytics work on Windows 8 and IE 10? 

### ISSUE THREAD

**Issue by Donquiweb** [MicrosoftDocs/powerbi-docs.fr-fr#7]
Hi, 

I try to work with the Adobe Analytics connector on Power BI Desktop but the authorization url on marketing.adobe.com seems to be forbidden for IE<11.

Do you know if the connector could work on Windows 8 and IE10 (we can't launch the URL:RES on Google chrome)?

Regards, 
Laurent

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 2b88aa9e-5500-8904-286c-4a6d22be2e9f
* Version Independent ID: b0faa18f-b2ca-4c95-3486-7227cfb31277
* Content: [Se connecter à Adobe Analytics dans Power BI Desktop - Power BI](https://docs.microsoft.com/fr-fr/power-bi/desktop-connect-adobe-analytics)
* Content Source: [powerbi-docs/desktop-connect-adobe-analytics.md](https://github.com/MicrosoftDocs/powerbi-docs.fr-fr/blob/live/powerbi-docs/desktop-connect-adobe-analytics.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by CeciAc** [comment]
Hello, @Donquiweb 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
