### ISSUE TITLE
Ne Fonctionne Pas !

### ISSUE THREAD

**Issue by Dadood** [MicrosoftDocs/powerbi-docs.fr-fr#9]
Bonjour, le tableau de bord Quickbooks ne se charge pas. Ceci doit être du à l'utilisation de la version Française de Quickbooks et de la non mise à jour de l'import Power BI.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: a74e3ffd-eefd-e93f-2a88-20d872922762
* Version Independent ID: 678b36be-0224-af5b-28d9-f457856611e7
* Content: [Se connecter à QuickBooks Online avec Power BI - Power BI](https://docs.microsoft.com/fr-fr/power-bi/service-connect-to-quickbooks-online#feedback)
* Content Source: [powerbi-docs/service-connect-to-quickbooks-online.md](https://github.com/MicrosoftDocs/powerbi-docs.fr-fr/blob/live/powerbi-docs/service-connect-to-quickbooks-online.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @SarinaJoan
* Microsoft Alias: **sarinas**

**Comment by CeciAc** [comment]
Bonjour @Dadood 

Merci pour votre contribution. Notre équipe peut uniquement répondre au feedback qui porte sur la documentation. 

Pour envoyer vos commentaires produit, nous vous invitons à cliquer sur le bouton « Envoyer des commentaires sur le produit » situé au bas de la page Docs. 

Si vous avez des commentaires sur la documentation, n’hésitez pas à nous les envoyer via ce canal. 

Votre contribution à nos articles est grandement appréciée.  

Cordialement, 
L’équipe Microsoft DOCS International
